home.index:
    path:     /
    defaults: { _controller: AppBundle:Student:index }

students.index:
    path:     /students/index
    defaults: { _controller: AppBundle:Student:index }

students.create:
    path:     /students/create
    defaults: { _controller: AppBundle:Student:create }

students.edit:
    path:     /students/{id}/edit
    defaults: { _controller: AppBundle:Student:edit }

students.delete:
    path:     /students/delete
    defaults: { _controller: AppBundle:Student:delete }

